name: First 
on:  
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print context info
        run: echo "${{ toJSON(github.event) }}"
