name: First 
on:  
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, edited, reopened]
env:
  APP_ENV: production
  APP_KEY: 123123
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_ENV: testing
    steps:
      - name: Get the repo code
        uses: actions/checkout@v3
      - name: Print env 
        run: echo "${{ env.APP_ENV }}"
      - name: Print secret
        run: echo "${{ env.APP_KEY }}"
#       - name: Cache deps
#         uses: actions/cache@v3
#         with:
#           path: |
#             ~/.cache/go-build
#             ~/go/pkg/mod
#           key: go-modules-${{ hashFiles('**/go.mod') }}
#       - name: Install deps
#         run: go mod vendor
#       - name: Test app
#         run: go test ./... > test.txt
#       - name: Artifact upload
#         uses: actions/upload-artifact@v3
#         with:
#           path: ./test.txt
#           name: test_art
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Get the repo code
#         uses: actions/checkout@v3
#       - name: Cache deps
#         uses: actions/cache@v3
#         with:
#           path: |
#             ~/.cache/go-build
#             ~/go/pkg/mod
#           key: go-modules-${{ hashFiles('**/go.mod') }}
#       - name: Install deps
#         run: go mod vendor
#       - name: Run the app
#         run: go run main.go
#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Get the repo code
#         uses: actions/checkout@v3
#       - name: Cache deps
#         uses: actions/cache@v3
#         with:
#           path: |
#             ~/.cache/go-build
#             ~/go/pkg/mod
#           key: go-modules-${{ hashFiles('**/go.mod') }}
#       - name: Install deps
#         run: go mod vendor
#       - name: Deploy 
#         run: echo Deploying!
