name: First 
on:  
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repo code
        uses: actions/checkout@v3
      - name: Test app
        run: go test ./...
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get the repo code
        uses: actions/checkout@v3
      - name: Run the app
        run: go run main.go
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy 
        run: echo Deploying!
