name: First 
on:  
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print something
        run: echo Hello World!
      - name: Print something else
        run: echo ANother world!
