name: First 
on:  
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repo code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-modules-${{ hashFiles('**/go.mod') }}
      - name: Install deps
        run: go mod vendor
      - name: Test app
        run: go test ./...
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repo code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-modules-${{ hashFiles('**/go.mod') }}
      - name: Install deps
        run: go mod vendor
      - name: Run the app
        run: go run main.go
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get the repo code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-modules-${{ hashFiles('**/go.mod') }}
      - name: Install deps
        run: go mod vendor
      - name: Deploy 
        run: echo Deploying!
